MyFirstMvc/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFirstMvc.Models;
using System.Text;
using System.Text.RegularExpressions;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Web.Security;

namespace MyFirstMvc.Controllers
{
    public class HomePageController : Controller
    {
        private bool islogin = false;
        private static string KEY = ":mlbjqys@111";
        //连接用户信息数据库
        private static string connectStr = 
            "Data Source=BRUCEZHANG-PC;Initial Catalog=Customer;Persist Security Info=True;User ID=sa;Password=1993";
        public SqlConnection connection = new SqlConnection(connectStr);
        public DataSet CustomerDS = new DataSet();
        public DataTable dt = new DataTable();

        public ActionResult Index()
        {
            if (Request.Cookies["account"] != null && Request.Cookies["ssid"] != null)
            {
                string account = Request.Cookies["account"].Value;
                string ssid = Request.Cookies["ssid"].Value;
                islogin = ssid.Equals(Encrypt(account+KEY));
            }
            ViewBag.i = islogin;
            SqlDataAdapter selectAdapter = 
                new SqlDataAdapter(@"select UserName,UserId from CustomerInfo",connection);
            selectAdapter.Fill(CustomerDS, "CustomerInfo");
            dt = CustomerDS.Tables["CustomerInfo"];
            int i = dt.Rows.Count; 
            return View(dt);
        }
        
        public ActionResult Register()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterModel rm)
        {
            //var rm = new RegisterModel { UserName = username,UserId = userid, UserPassWord = userpassword };

            if (rm.UserName == null)
            {
                ModelState.AddModelError("userName", "用户名不能为空。");
            }
            if (rm.UserId.Length != 3)
            {
                ModelState.AddModelError("userId", "ID必须为三位数字。");
            }
            if (rm.UserPassWord.Length != 3)
            {
                ModelState.AddModelError("userPassword", "密码必须为三位。");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    string sqlcom =
                        @"insert into CustomerInfo values('" + rm.UserId + "','" + rm.UserName + "','" + rm.UserPassWord + "')";
                    SqlDataAdapter insertAdapter = new SqlDataAdapter(sqlcom, connection);
                    insertAdapter.Fill(CustomerDS,"CustomerRegist");
                    return Redirect("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("UserId",ex.Message);
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(RegisterModel rm)
        {
            SqlDataAdapter longinAdapter =
                new SqlDataAdapter(@"select UserId,UserPassword from CustomerInfo", connection);
            longinAdapter.Fill(CustomerDS, "LogCustomerInfo");
            dt = CustomerDS.Tables["LogCustomerInfo"];
            foreach (System.Data.DataRow dr in dt.Rows)
            {
                if ( ((string)dr["UserId"]).Trim() == rm.UserId )
                {
                    if (((string)dr["UserPassWord"]).Trim() == rm.UserPassWord)
                    {
                        string account = rm.UserId;
                        string password = rm.UserPassWord;
                        string ssid = Encrypt(account + KEY);
                        HttpCookie accountCookie = new HttpCookie("account", account);
                        accountCookie.Expires = DateTime.Now.AddDays(1);
                        accountCookie.Path = "/";
                        HttpCookie ssidCookie = new HttpCookie("ssid", ssid);
                        ssidCookie.Expires = DateTime.Now.AddDays(1);
                        ssidCookie.Path = "/";
                        Response.Cookies.Add(accountCookie);
                        Response.Cookies.Add(ssidCookie);

                        return Redirect("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("userPassword", "密码错误，请重新输入.");
                        return View();
                    }
                }

            }
            ModelState.AddModelError("userId", "账户不存在，请重新输入.");
            return View();
        }

        public ActionResult LogOut()
        {
            Response.Cookies["account"].Expires = DateTime.Now.AddDays(0);
            Response.Cookies["ssid"].Expires = DateTime.Now.AddDays(0);
            return Redirect("Index");
        }

        public ActionResult UpLoad()
        {
            string del = @"delete from MapInfo where enemyName=' ' ";
            SqlDataAdapter infodel = new SqlDataAdapter(del, connection);
            infodel.Fill(CustomerDS, "delete");
            if (Request.Cookies["account"] != null && Request.Cookies["ssid"] != null)
            {
                string account = Request.Cookies["account"].Value;
                string ssid = Request.Cookies["ssid"].Value;
                islogin = ssid.Equals(Encrypt(account + KEY));
            }
            ViewBag.i = islogin;
            return View();
        }
        [HttpPost]
        public ActionResult UpLoad(HttpPostedFileBase Uploadfile,EnemyInfoModel em)
        {
            if (Uploadfile == null)
            {
                ModelState.AddModelError("picUpload", "文件未选中，请重新选择。");
                return View();
            }
            double size = Uploadfile.ContentLength;
            string mime = Uploadfile.ContentType;
            string fileName = Uploadfile.FileName;
            //正则表达式判断后缀名
            Regex reg = new Regex(@"\.(jpg|jpeg|bmp|gif|png)$");
            if (!reg.IsMatch(fileName.ToLower()))
            {
                ModelState.AddModelError("picUpload", "文件格式不正确，请选择后缀名为jpg,jpeg,bmp,gif,png的图片。");
                return View();
            }
            if (em.EnemyName == null || em.EnemyName == "")
            {
                ModelState.AddModelError("controller", "请输入敌人姓名。");
                return View();
            }
            //string newFileLocation = @"D:/Files/";
            //判断路径存在与否
            string savepath = Server.MapPath("~/Images/enemy/");
            if (!Directory.Exists(savepath))
                {
                    Directory.CreateDirectory(savepath);
                }
            //操作数据库
            try
            {
                string suffix = reg.Match(fileName).ToString();
                em.EnemyPic = System.Guid.NewGuid() + suffix;
                string sqlcom =
                    @"insert into MapInfo values('" + em.EnemyPic + "','" + em.EnemyName + "','"
                    + em.EnemyBlood + "','" + em.EnemySouls + "','" + em.EnemyItem + "')";
                SqlDataAdapter insertAdapter = new SqlDataAdapter(sqlcom, connection);
                insertAdapter.Fill(CustomerDS, "UploadMapInfo");
            }
            catch (Exception ex){
                ModelState.AddModelError("controller", ex.Message);
                return View();
            }
            //保存图片
            Uploadfile.SaveAs(savepath + em.EnemyPic);

            return Content("上传成功");
            /*使用uploadify控件上传文件
             * if (Uploadfile != null)
            {
                try
                {
                    string filePath = Server.MapPath("~/Images/enemy/");
                    //判断路径是否存在
                    if (!Directory.Exists(filePath))
                    {
                        Directory.CreateDirectory(filePath);
                    }
                    string fileName = Path.GetFileName(Uploadfile.FileName); //原始文件名称
                    string fileExtension = Path.GetExtension(fileName);     //文件扩展名
                    string saveName = Guid.NewGuid().ToString() + fileExtension;
                    Uploadfile.SaveAs(filePath + saveName);
                    
                    return Json(new { Success = true, FileName = fileName, SaveName = saveName });
                }
                catch (Exception ex)
                {
                    return Json(new { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { Success = false, Message = "请选择要上传的文件!" }, JsonRequestBehavior.AllowGet);
            }*/
        }
        //加密
        public static string Encrypt(string str)
        {
            return FormsAuthentication.HashPasswordForStoringInConfigFile(str, "MD5");
        }
        //解密
        public static string Decrypt(string str)
        {
            return FormsAuthentication.Decrypt(str).Name.ToString();
        }
    }
}

MyFirstMvc/Views/HomePage/Index.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.3org/TR/xhtml1-transitional.dtd">
@model System.Data.DataTable
@{
    //Layout = "~/Views/_Layout.cshtml";
}
@{
    ViewBag.Title = "Index";
}
<html>
  <head>
    <title>DarkSoulsIII</title>
    <link rel="Shortcut Icon" href="/Images/favicon.ico" />
    <link rel="Stylesheet" href="../../Scripts/bootstrap/css/bootstrap.min.css" />
    <script type="text/javascript" src="../../Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript" src="../../Scripts/bootstrap/js/bootstrap.min.js"></script>
    <link rel="Stylesheet" type="text/css" href="../../Content/HomePageIndex.css" />
    <script type="text/javascript">
        $(document).ready(function () {
            //页面跳转
            $("#register").click(function () {
                location.href = "/HomePage/Register";
                return false;
            });
            $("#login").click(function () {
                location.href = "/HomePage/LogIn";
                return false;
            });

            //显示或隐藏部分内容
            var $userinfo = $("ul#userinfo li:gt(4)");
            $userinfo.hide();
            $("#show").toggle(function () {
                $userinfo.show(600);
                $("#show").find("span").text("隐藏部分用户");
            },
                    function () {
                        $userinfo.hide(600);
                        $("#show").find("span").text("显示全部用户");
                    });

            $("a").hover(function () {
                $(this).css("color", "red");
            }, function () {
                $(this).css("color", "#333333");
            });
            //动态修改样式
            $("input#cc").click(function () { $("ul#userinfo li").attr("class", "another") });
            $("input#ac").click(function () { $("ul#userinfo li").addClass("another") });
            $("input#tc").click(function () { $("ul#userinfo li").toggleClass("another") });
            //$("ul#userinfo li").wrapAll("<strong></strong>");

            //自定义超链接提示
            $("a.tooltip").mouseover(function (e) {
                this.Mytitle = this.title;
                this.title = "";
                var ele = $("<div id='elem'>" + this.Mytitle + "</div>");
                $("body").append(ele);
                $("#elem").show("fast");
            }).mouseout(function () {
                this.title = this.Mytitle;
                $("#elem").remove().hide();
            }).mousemove(function (e) {
                $("#elem").css({
                    "top": e.pageY + 10,
                    "left": e.pageX + 20
                });
            });

            //判断鼠标在页面中的左右移动并附加相应动画1
            $("#defaultshow").hover(function () {
                $("#defaultshow img").stop().animate({ left: "+=10px" }, "1000");

            }, function () {
                $("#defaultshow img").stop().animate({ left: "-=10px" }, "1000");

            });
            //动画2
            /*var lastX = 296; 
            $("#defaultshow").mousemove(function (e) {
            if (e.pageX > lastX) {
            $(this).animate({ left: '256px' }, "fast");
            } else if (e.pageX < lastX) {
            $(this).animate({ left: '336px' }, "fast");
            }
            lastX = e.pageX;
            });*/

            //二级目录显示
            $(".mlname").toggle(function () {
                $(this).next().show(500);
            }, function () {
                $(this).next().hide(500);
            });
            $(".menulist").mousemove(function (e) {
                $("#top").attr("value", e.setoffY);
                $("#left").attr("value", e.setoffX);
            });
            //二级目录内容略缩图动态显示
            $(".menulist1>span").hover(function (e) {
                $(this).css("color", "red");
                this.Mytitle = this.title;
                this.title = "";
                $("#menulistimg").show().attr("src", this.Mytitle);
            }, function (e) {
                $(this).css("color", "white");
                this.title = this.Mytitle;
                $("#menulistimg").hide().attr("src", "");
            });
            //略缩图跟随鼠标，使用鼠标相对div的位置赋值，offsetX、pageX、screenX和clientX区别。
            $(".menulist1>span").mousemove(function (e) {
                $("#menulistimg").css({
                    "top": e.clientY - 70,
                    "left": e.clientX + 10
                });
            });

            $("#logo").click(function () {
                $("#infoshow").empty();
                $("#defaultshow").show();
            });
            //ajax加载网页
            $(".menulist1>span").click(function () {
                //location.href = "/DarkSoulsMap/"+this.id;
                $("#infoshow").empty();
                $.ajax({
                    url: "/DarkSoulsMap/" + this.id,
                    type: "GET",
                    dataType: "text",
                    success: function (data) {
                        $("#defaultshow").hide();
                        $("#infoshow").append(data);
                        $("#infoshow").show();
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Request.Status:\t" + XMLHttpRequest.Status + "\ntextStatus:\t" + textStatus + "\nerrorThrown:\t" + errorThrown + "\n");
                    }
                });
            });

        });     
    </script>
  </head>
  <body>
    <div class="maindiv">
        <div class="menu">
            <div id="logo">
            </div>
            <div class="menulist">
                <ul id="list">
                    <li class="listdetail" id="mll1"><span class="mlname" id="mapinfo">地图信息</span>
                        <div class="menulist1" id="map">
                            <span id="Map1" title="../../Images/map/map1.jpg">灰烬墓地</span><br />
                            <span id="Map2" title="../../Images/map/map2.jpg">传火祭祀场</span><br />
                            <span id="Map3" title="../../Images/map/map3_1.jpg">洛斯里克的高墙</span><br />
                            <span id="Map4" title="../../Images/map/map4.jpg">不死街</span><br />
                        </div>
                    </li>
                    <li class="listdetail" id="mll2"><span class="mlname" id="bossinfo">领主信息</span>
                        <div class="menulist1" id="boss">
                            <span id="Boss1" title="../../Images/boss/boss1.jpg">灰烬审判者古达</span><br />
                            <span id="Boss2" title="../../Images/boss/boss2.jpg">冷冽谷的波尔多</span><br />
                            <span id="Boss3" title="../../Images/boss/boss3.jpg">冷冽谷的舞娘</span><br />
                        </div>
                    </li>
                    <li class="listdetail" id="mll3"><span class="mlname" id="weaponinfo">武器信息</span>
                        <div class="menulist1" id="weapon">
                            <span id="Weapon1" title="">直剑</span>
                            <span id="Weapon2" title="">巨剑</span>
                            <span id="Weapon3" title="">特大剑</span>
                        </div>
                    </li>
                    <li class="listdetail" id="mll4"><span class="mlname">防具信息</span>
                        <div class="menulist1" id="fangju">
                            <span id="fangju1" title="">布甲</span>
                            <span id="fangju2" title="">皮甲</span>
                            <span id="fangju3" title="">重甲</span>
                        </div>
                    </li>
                </ul>
            </div>
            <img id="menulistimg" src="" alt="" />
        </div>
        <div class="mainshow">
            <div id="defaultshow">
                <img src="/Images/bg_home_character.png" alt="bg" style="position: relative;" />
            </div>
            <div id="infoshow">
            </div>
        </div>
        <div class="adshow">
            <ul class="fr">
                <li class="fore1">
                @{
                    if(!ViewBag.i){
                        <a href="" class="top" id="login">登录</a>
                    }
                    else{
                        <a href="" id="userintroduce">欢迎:@Request.Cookies["account"].Value</a>
                        <a href="/HomePage/LogOut" id="logout">注销</a>
                    }
                 }
                <a href="" class="top"id="register">注册</a>
                </li>
            </ul>
            <div class="regus">
                <a href="" class="csschange" id="cc"  >修改Class</a>
                <a href="" class="csschange" id="ac"  >增加Class</a>
                <a href="" class="csschange" id="tc"  >切换Class</a>
                <p class="high" style="position:relative;left:20%;">
                    已注册用户信息:</p>
                <ul id="userinfo">
                    @foreach (System.Data.DataRow item in Model.Rows)
                    {
                        <li class="high">姓名：@item["UserName"] ID：@item["UserId"]
                        </li>
                    }
                </ul>
                <a href="" title="超链接提示" id="show" class="tooltip"><span>显示全部用户</span></a><br />
            </div>
        </div>
    </div>
  </body>
</html>

MyFirstMvc/Views/HomePage/LogIn.cshtml
@model MyFirstMvc.Models.RegisterModel
@{
    //Layout = "~/Views/_Layout.cshtml";
    }
@{
    ViewBag.Title = "LogIn";
}
<html>
    <head>
        <link rel="Stylesheet" href="../../Scripts/bootstrap/css/bootstrap.min.css"/>
        <script type="text/javascript" src="../../Scripts/jquery-3.1.1.js"></script>
        <script type="text/javascript" src="../../Scripts/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#userId").focus(function () {
                    if ($(this).val() == "请输入帐号")
                        $(this).val("");
                });
                $("#userId").blur(function () {
                    if ($(this).val() == "")
                        $(this).val("请输入帐号");
                });
                $("#userPassword").focus(function () {
                    if ($(this).val() == "请输入密码") {
                        $(this).val("");
                        //$(this).attr("type", "password");
                    }
                });
                $("#userPassword").blur(function () {
                    if ($(this).val() == "") {
                        // $(this).attr("type", "text");
                        $(this).val("请输入密码");
                    }
                });
                var offset = $("div#submit").offset();
            });
        </script>
        <title>LogIn</title>
        <link rel="Shortcut Icon" href="/Images/favicon.ico" />
        <style type="text/css">
            h2
            {
                position:absolute;
                left:44%
                }
            #submit
            {
                position:absolute;
                left:40%;
                top:15%;
                border:black solid thin;
                }
        </style>
    </head>
    <body>
        <h2>LogIn</h2>
        <a href="http://localhost:7146/">首页</a>
        <div id="submit" style="display:none;">
        @using (Html.BeginForm("LogIn", "HomePage", FormMethod.Post))
        {
            @Html.Label("用户ID")<br />
            @Html.TextBox("userId","请输入帐号")
            @Html.ValidationMessage("userId") <br />
            @Html.Label("用户密码")<br />
            //<input type="password" name="userPassword" value = "请输入密码"/>
            @Html.Password("userPassword", "请输入密码")
            @Html.ValidationMessage("userPassword") <br />
            <input id="login" type ="submit" value="LogIn" />
        }
        </div>
        <div style="padding:100px 100px 10px;">
            <form class="form-horizontal" role="form" action="LogIn" method="post" enctype="application/x-www-form-urlencoded">
              <div class="form-group">
                <label class="col-sm-5 control-label" for="name">名称</label>
                <div class="col-sm-2">
                  <input type="text" class="form-control" id="name" name="userId" placeholder="请输入名称" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-5 control-label" for="password">密码</label>
                <div class="col-sm-2">
                  <input type="password" class="form-control" id="password" name="userPassword" placeholder="请输入密码" />
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-5 control-label">电话</label>
                <div class="col-sm-2">
                  <input type="text" class="form-control" placeholder="请输入电话号码" disabled />
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-5 col-sm-2">
                  <div class="form-group checkbox">
                    <label>
                      <input type="checkbox" />记住我
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-5 col-sm-2">
                  <button type="submit" class="btn btn-default col-sm-10">登录</button>
                </div>
              </div>
            </form>
          </div>
    </body>
</html>

MyFirstMvc/Views/HomePage/Register.cshtml
@model MyFirstMvc.Models.RegisterModel
@{
    //Layout = "~/Views/_Layout.cshtml";
    }
@{
    ViewBag.Title = "Register";
}
<html>
    <head>
    <script type="text/javascript" src="../../Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $("#RegSubmit").click(function () {
                var up = $("#userPassword").val();
                var up1 = $("#userPassword1").val();
                var ui = $("#userId").val();
                var un = $("userName").val();
                if (up == "" || up1 == "" | ui == "" | un == "") {
                    $("div#msg").html("<p>请输入完整内容后提交.</p>");
                    return false;
                }
                if (up != up1) {
                    $("div#msg").html("<p>两次输入的密码不同,请重新输入.</p>");
                    return false;
                }
            });
        });
    </script>
    <title>Register</title>
    <link rel="Shortcut Icon" href="/Images/favicon.ico" />
    <style type="text/css">
        body{}
        h2{ position:absolute; left:40%;}
        #register{position:absolute; border:black solid thin; left:36%; top:10%;}
    </style>
    </head>
    <body>
    <h2>Regist</h2>
    <a href="http://localhost:7146/">首页</a>
        <div id="register">
            @using (Html.BeginForm("Register", "HomePage", FormMethod.Post))  
                {  
                    @Html.Label("用户姓名："); <br />
                    @Html.TextBox("userName");<br />
                    @Html.Label("用户帐号：") <br />
                    @Html.TextBox("userId");
                    @Html.ValidationMessage("userId")<br />  
                    @Html.Label("输入密码："); <br />
                    @Html.Password("userPassword");<br />
                    @Html.Label("再次输入密码：");<br />
                    @Html.Password("userPassword1");
                    @Html.ValidationMessage("userPassword") <br />
                    <input id="RegSubmit" type="submit" value="提交" />  
                } 
                <div id="msg" style="color:Red"></div> 
        </div>
    </body>
</html>

MyFirstMvc/Views/HomePage/UpLoad.cshtml
@model MyFirstMvc.Models.EnemyInfoModel
@{
    //Layout = "~/Views/_Layout.cshtml";
    }
@{
    ViewBag.Title = "UpLoad";
}
<html>
    <head>
    <link href="../../Scripts/uploadify/uploadify.css" type="text/css" rel="Stylesheet" />
    <script type="text/javascript" src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="../../Scripts/uploadify/jquery.uploadify.min.js"></script>
    <script type="text/javascript" src="../../Scripts/uploadify/jquery.uploadify.js"></script>
    <script type="text/javascript" src="../../Scripts/jquerySession.js"></script>
    <script type="text/javascript" src="../../Scripts/jquery.cookie.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //上传图片预览
            $("#filupload").on("change", function () {
                var files = this.files ? this.files : [];
                if (!files.length || !window.FileReader) return;
                if (/^image/.test(files[0].type)) {
                    var reader = new FileReader();
                    reader.readAsDataURL(files[0]);
                    reader.onloadend = function () {
                        $("#uploadpreview").attr("src", this.result).show();
                    }
                }
            });
            //表单提交前的判断
            $("#uploadtable").click(function () {
                if ($("#filupload").val() == null || $("#filupload").val() == "") {
                    $("#ulpicer").show();
                    return false;
                }
                else {
                    $("#ulpicer").hide();
                    if ($("#enna").val() == null || $("#enna").val() == "") {
                        $("#upnaer").show();
                        return false;
                    }
                    else {
                        $("#upnaer").hide();
                        $("form").submit();
                    }
                }
            });
        });
    </script>
    <title>UpLoad</title>
    <link rel="Shortcut Icon" href="/Images/favicon.ico" />
    <style type="text/css">
        *{ margin:0; left:0;}
        h2{position:absolute;left:44% }
        .ultable{position:absolute;left:34%;top:15%;}
        .inputerror{color:Red;}
        .adshow{position:absolute; right:5%;}
        #uploadtable{ position:relative; left:45%;}
        #uploadpreview{display:none;width:80px;height:85px;}
    </style>
    </head>
    <body>
    <h2>UpLoad</h2>
    <div class="adshow">
        <ul class="fr" style="list-style-type:none;">
            <li class="fore1">
            @{
                <a href="http://localhost:7146/">首页</a>
                if(!ViewBag.i){
                   <a href="/HomePage/LogIn" class="top" id="login">登录</a>
                }
                else{
                   <a href="" id="userintroduce">欢迎:@Request.Cookies["account"].Value</a>
                   <a href="/HomePage/LogOut" id="logout">注销</a>
                }
                }
                <a href="/HomePage/Register" class="top"id="register">注册</a>
            </li>
        </ul>
    </div>
    <div class="ultable">
        <div class="form-group">
            <label class="col-sm-4 control-label" for="inputfile">文件输入</label>
            <div class="col-sm-2">
              <input type="file" id="inputfile" />
              <p class="help-block">选择文件在这里</p>
            </div>
        </div>
    @{
        if(ViewBag.i){
        <form id="uploadform" action="UpLoad" method="post" enctype="multipart/form-data">
            <table border="1" cellpadding="12">
            <caption>update</caption>
                <tr>
                    <td>敌人图片:</td>
                    <td><img id="uploadpreview" src="" alt=""/>
                    <input id="filupload" type="file" name="Uploadfile" />
                    <p id="ulpicer" style="display:none;">文件未选中，请重新选择</p>
                    @Html.ValidationMessage("picUpload")
                    </td>
                </tr>
                <tr>
                    <td>敌人姓名:</td>
                    <td><textarea id="enna" name="enemyName" rows="1" cols="20"></textarea>
                    <p id="upnaer" style="display:none;">请输入敌人姓名</p>
                    </td>
                </tr>
                <tr>
                    <td>敌人血量:</td>
                    <td><textarea id="enbl" name="enemyBlood" rows="1" cols="20"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>携带灵魂:</td>
                    <td><textarea id="enso" name="enemySouls" rows="1" cols="20"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>掉落物品:</td>
                    <td><textarea id="enit" name="enemyItem" rows="2" cols="20"></textarea>
                    </td>
                </tr>
            </table>
            <input id="uploadtable" type="button" value="提交"/> <br />
            @Html.ValidationMessage("controller")
        </form>
        }
        else{
            <p>登录后获得修改权限</p>
        }
        }
    </div>
      @*<div>
        @using (@Html.BeginForm("UpLoad", "HomePage", FormMethod.Post, 
            new { enctype = "multipart/form-data" }))
        {
            @Html.TextBox("Uploadfile", null, new { type = "file" });
            <br />
          
            <input id="upload" type="submit" value="上传" />
            @Html.ValidationMessage("upload");
        }
        <a href = "javascript:$('#file_upload').uploadify('upload');">上传图片</a>
        <a href = "javascript:$('#file_upload').uploadify('cancel');">取消上传</a>
      </div>*@
    </body>
</html>